### ISSUE TITLE
1.26 cannot connect to ethermine. 1.25 working

### ISSUE THREAD

**Issue by sp-hash** [sp-hash/TeamBlackMiner#142]
@bitcointalk
@ethermine

Quote from: sp_ on Today at 06:25:09 PM
Quote from: symplink on Today at 06:16:34 PM
No, it is not working.

Final command - hiveos: -cl-devices [0,1,2,3,4,5,6] --no-cpu --no-verbose
Tried w/o --no-cpu too
The miner is crashing, if you want the crash file report, let me know

If it is not crashing , I saw a strange curl error, but only once , cannot copy it

You can register a ticket here:

https://github.com/sp-hash/TeamBlackMiner/issues

Are your rigs connected through a wifi router? We are blocking proxy servers so you have to connect to the pool directly.

Cable, not wifi.No proxies. TBM 1.25 working ok, tested again.
Same network, all the nvidia are working.
I will complete a ticket.

Maybe could help in quick way:
temp: 0                                                                                                                                       
fan: 0                                                                                                                                         
core: 0                                                                                                                                       
mem: 0                                                                                                                                         
power: 0                                                                                                                                       
hashrate: 65.08 MH/s                                                                                                                           
hashrate (avg): 59.31 MH/s                                                                                                                     
accepted: 0                                                                                                                                   
rejected: 0                                                                                                                                   
board: gfx1030                                                                                                                                 
temp: 43                                                                                                                                       
fan: 0                                                                                                                                         
core: 0                                                                                                                                       
mem: 0                                                                                                                                         
power: 90                                                                                                                                     
hashrate: 65.02 MH/s                                                                                                                           
hashrate (avg): 59.61 MH/s                                                                                                                     
accepted: 0                                                                                                                                   
rejected: 0                                                                                                                                   
job: d1530d                                                                                                                                   
bondary: 00000000ffff0000000000000000000000000000000000000000000000000000                                                                     
header: d1530ddf4ce43324e12d472ea98228b789403d1f61dc5ba7e18b59c1ceeac83f                                                                       
seed: 05a006f672938919fddc06c085dd11fad80cddcdefeed085e1437db1109b4d74                                                                         
epoch: 454                                                                                                                                     
block: -1                                                                                                                                     
start_nonce: 9117537445611569152                                                                                                               
extranonce_len: 4                                                                                                                             
difficulty: 1.000000                                                                                                                           
send buffer: ''                                                                                                                               
send buffer length: 0                                                                                                                         
recv buffer: '{"id":null,"method":"mining.notify","params":["d1530d","05a006f672938919fddc06c085dd11fad80cddcdefeed085e1437db1109b4d74","d1530d
df4ce43324e12d472ea98228b789403d1f61dc5ba7e18b59c1ceeac83f",false]}                                                                           
'                                                                                                                                             
recv buffer length: 197                                                                                                                       
recv buffer more data flag: -311943624

**Comment by binaryf** [comment]
The output says this crash is after connect and authorize.
A crash is a serious problem, can you provide a copy of the console output or a screenshot .

**Comment by itvalentino76** [comment]
GPU4 gfx1030 17GB added to miner as OpenCL device
00:00:00 [2021-11-20 10:57:31.191] GPU5 gfx1030 17GB added to miner as OpenCL device
00:00:00 [2021-11-20 10:57:31.191] GPU6 gfx1030 17GB added to miner as OpenCL device
00:00:00 [2021-11-20 10:57:31.192] Trying eth.2miners.com:2020 (ethash)
00:00:00 [2021-11-20 10:57:31.192] Cannot connect to mining pool. Retrying...
00:00:00 [2021-11-20 10:57:31.192] Sleeping for 17 seconds

The application has crashed.                                                                                                                   
A crash report is written to file crash_report.txt                                                                                             
                                                                                                                                               
                                                                                                                                               
teamblackminer exited (exitcode=0), waiting to cooldown a bit
                                                                                                                                               
Skipping miner log rotation due to execution time < 30sec

the crash_report file is:

emp: 0                                                                                                                                        
fan: 0                                                                                                                                         
core: 0                                                                                                                                        
mem: 0                                                                                                                                         
power: 0                                                                                                                                       
hashrate: 65.08 MH/s                                                                                                                           
hashrate (avg): 59.31 MH/s                                                                                                                     
accepted: 0                                                                                                                                    
rejected: 0                                                                                                                                    
board: gfx1030                                                                                                                                 
temp: 43                                                                                                                                       
fan: 0                                                                                                                                         
core: 0                                                                                                                                        
mem: 0                                                                                                                                         
power: 90                                                                                                                                      
hashrate: 65.02 MH/s                                                                                                                           
hashrate (avg): 59.61 MH/s                                                                                                                     
accepted: 0                                                                                                                                    
rejected: 0                                                                                                                                    
job: d1530d                                                                                                                                    
bondary: 00000000ffff0000000000000000000000000000000000000000000000000000                                                                      
header: d1530ddf4ce43324e12d472ea98228b789403d1f61dc5ba7e18b59c1ceeac83f  
seed: 05a006f672938919fddc06c085dd11fad80cddcdefeed085e1437db1109b4d74                                                                         
epoch: 454                                                                                                                                     
block: -1                                                                                                                                      
start_nonce: 9117537445611569152                                                                                                               
extranonce_len: 4                                                                                                                              
difficulty: 1.000000                                                                                                                           
send buffer: ''                                                                                                                                
send buffer length: 0                                                                                                                          
recv buffer: '{"id":null,"method":"mining.notify","params":["d1530d","05a006f672938919fddc06c085dd11fad80cddcdefeed085e1437db1109b4d74","d1530d
df4ce43324e12d472ea98228b789403d1f61dc5ba7e18b59c1ceeac83f",false]}                                                                            
'                                                                                                                                              
recv buffer length: 197                                                                                                                        
recv buffer more data flag: -311943624  

accepted: 0


bondary: 00000000ffff0000000000000000000000000000000000000000000000000000
header: d1530ddf4ce43324e12d472ea98228b789403d1f61dc5ba7e18b59c1ceeac83f
seed: 05a006f672938919fddc06c085dd11fad80cddcdefeed085e1437db1109b4d74
epoch: 454avg): 59.31 MH/s
block: -1 0vg): 59.30 MH/sL 2.1 AMD-APP (3180.7)
start_nonce: 9117537445611569152

**Comment by binaryf** [comment]
And this is both ethermine and 2miners ?

**Comment by binaryf** [comment]
I am working on it right now.
Seems to be fine in Windows.
Will try HiveOs and Ubuntu.

**Comment by binaryf** [comment]
Thanks :)

**Comment by itvalentino76** [comment]
It is independent from pool.
It manifests on hiveos

**Comment by binaryf** [comment]
Yes. Found the bug. Stratum connect function is rewritten.
Thanks for the help to fix this issue.

**Comment by itvalentino76** [comment]
No prob, glad I helped.
